### ISSUE TITLE
"quickstart_etl" not available from the `dagster project` CLI

### ISSUE THREAD

**Issue by rahulmahajan511** [dagster-io/quickstart-etl#1]
I am trying to Bootstrap own Dagster project with this example using command
dagster project from-example --name my-dagster-project --example quickstart_etl

but i end up with with below error 
Example "quickstart_etl" not available from the `dagster project` CLI

**Comment by yuhan** [comment]
Hi @rahulmahajan511 Thanks for opening this issue! I believe you caught it right before the release. "quickstart_etl" should be now available from the `dagster project` CLI
